### ISSUE TITLE
OSError 'Directory not empty' while running 'pyrpipe_diagnostic test'

### ISSUE THREAD

**Issue by wolfylair** [urmi-21/pyrpipe#18]
Hi,

I just installed pyrpipe and I ran the testing commands 'pyrpipe_diagnostic test' but it gave me errors as follows:

```
Traceback (most recent call last): 
 file "/home/sirius/anaconda3/envs/pyrpipe/bin/pyrpipe_diagnostic", line 10, in <module>      
   sys.exit(main())                                                                                                              
File "/home/sirius/anaconda3/envs/pyrpipe/lib/python3.8/site-packages/pyrpipe/__diagnostic__.py", line 274, in main               
    testsra()                                                                                                                     File "/home/sirius/anaconda3/envs/pyrpipe/lib/python3.8/site-packages/pyrpipe/__diagnostic__.py", line 232, in testsra            
    test_sratools.runtest()                                                                                                       File "/home/sirius/anaconda3/envs/pyrpipe/lib/python3.8/site-packages/pyrpipe/test_sratools.py", line 20, in runtest              
    os.rmdir(sraob.directory)                                                                                                   
OSError: [Errno 39] Directory not empty: './pyrpipe_sratest/ERR726985'
```

I also looked at the config-TOOLS and I set the settings as "user repository" (No word 'public' exists), but with no help.

Could you please help me solve the issue? I haven't run actual program yet but I guess something's off if there's an error in testing commands.

Best

**Comment by urmi-21** [comment]
Hi @wolfylair,
This is happening because of SRA-Tools. The test command is supposed to download data from SRA into `pyrpipe_sratest/<SRA_id>` directory. I have noticed in some cases data gets downloaded to `pyrpipe_sratest/<SRA_id>/<SRA_id>` and then when pyrpipe attempts to remove  `pyrpipe_sratest/<SRA_id>` it throws this error. 

**However, pyrpipe should work as expected as I modified the behaviour  of SRA class to handle this.**

I will improve this test in future release. Also, if you could confirm the version of your SRA-Tools that would be helpful.

Please let me know if you have any other questions. Thanks

**Comment by wolfylair** [comment]
Hi, 

Thank you for your reply! My SRA-tools version is 2.10.9. You can close this thread now and i'll let you know if having other issues.

Best
