### ISSUE TITLE
basictest.py: sam_to_bam() got an unexpected keyword argument 'threads'

### ISSUE THREAD

**Issue by wolfylair** [urmi-21/pyrpipe#19]
Hi,

I am running basictest.py for Pyrpipe but i got the issues as follows:

ERROR basictest.py - TypeError: sam_to_bam() got an unexpected keyword argument 'threads'

I tried both in my laptop and on the Slurm server but neither worked.

Could you please help find out the possible issue?

Thank you!

**Comment by urmi-21** [comment]
Hi @wolfylair, please ignore the `basictest.py` script, that file is not a part of the test suite and may contain older code. I will remove that file in the future. Please see the [case studies](https://github.com/urmi-21/pyrpipe/tree/master/case_studies) if you are looking for examples. There is also a getting [started tutorial](https://pyrpipe.readthedocs.io/en/latest/tutorial/index.html).


PS: The error states [sam_to_bam()](https://github.com/urmi-21/pyrpipe/blob/f999f9d8689c43aabdd5b621511e4299cbba2e28/pyrpipe/tools.py#L44) got unknown param `threads`. This is because threads are specified while creating the [Samtools](https://github.com/urmi-21/pyrpipe/blob/f999f9d8689c43aabdd5b621511e4299cbba2e28/pyrpipe/tools.py#L35) object and no such param exists for `sam_to_bam()`

**Comment by wolfylair** [comment]
Hi, thanks for the clarification. I guess it makes sense now. You can close the thread.
